### ISSUE TITLE
missing terrar for windows

### ISSUE THREAD

**Issue by peterminh227** [acados/tera_renderer#5]
Hi, 

I am using tera to generate C code in Windows (10) PC but I got this error, I have checked in the releases tag, there is no binary file for windows as well. 

Error using matlab.internal.webservices.HTTPConnector/copyContentToFile (line 412)
The server returned the status 404 with message "Not Found" in response to the request to URL
https://github.com/acados/tera_renderer/releases/download/v0.0.30/t_renderer-v0.0.30-windows.exe.

**Comment by FreyJo** [comment]
Hi @peterminh227 ,

I just managed to fix the tera binary generation on Windows.
See the latest release:
https://github.com/acados/tera_renderer/releases/tag/v0.0.34
The previous release where Windows binary generation worked is:
https://github.com/acados/tera_renderer/releases/tag/v0.0.20

I will bump the `tera_renderer` version in `acados` in my latest PR.
Then automatic download through Matlab should be fixed.

In the meantime, you can set up `t_renderer` manually:

I copied the following instructions from https://docs.acados.org/interfaces/index.html

> In order to be able to successfully render C code templates, you need to download the t_renderer binaries for your platform from https://github.com/acados/tera_renderer/releases/ and place them in <acados_root>/bin (please strip the version and platform from the binaries (e.g. t_renderer-v0.0.20 -> t_renderer). Notice that you might need to make t_renderer executable.

**Comment by FreyJo** [comment]
Update: this is the bump commit
https://github.com/acados/acados/pull/551/commits/2e968ab4ed973987e7e1dd135ee10fb084528538

It is included in this PR, which you can already checkout
https://github.com/acados/acados/pull/551
